### ISSUE TITLE
Rubocop Rails/Present problem?

### ISSUE THREAD

**Issue by delphaber** [Shopify/erb-lint#100]
When I run `erblint`, I get only 1 warning for `Rails/Present` instead of 2. I don't know if this is a problem with `erblint` or `rubocop`. Am I doing something wrong?

## Steps to reproduce

```bash
$ erblint --version
0.0.26
```

```bash
$ rubocop --version
0.59.2
```

Erb file name `foo.html.erb`
```erb
<% unless @foo.blank? %>
  <h1>Hello</h1>
<% end %>

<span class="<%= 'foo' unless @foo.blank? %>"></span>
```
erblint config
```yaml
---
linters:
  Rubocop:
    enabled: true
    rubocop_config:
      Rails:
        Enabled: true
      Rails/Present:
        Enabled: true
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingBlankLines:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
```

```bash
 ↳ $ erblint foo.html.erb
Linting 1 files with 13 linters...

Rails/Present: Use `if @foo.present?` instead of `unless @foo.blank?`.
In file: foo.html.erb:5

1 error(s) were found in ERB files
```

As you can see, `erblint` found only the `unless .blank?` in line 5 and not the one in line 1. How come? 🤔

**Comment by EiNSTeiN-** [comment]
This is a limitation that comes from the way ruby is parsed out of ERB. Each erb tag is parsed in isolation so `unless foo.present?` is parsed and is ignored because it is not valid syntax. In an ideal world we would build a single AST that contains both the html and ruby nodes, but that's not how things are done right now :/

**Comment by delphaber** [comment]
Thank yo @EiNSTeiN- :) At least I know it's not just a typo I made :D

Great work for this gem!

**Comment by delphaber** [comment]
Ops... I closed the Issue for mistake. Reopen it if you want :)

**Comment by oliverbarnes** [comment]
👋 @EiNSTeiN- why is `<% unless @foo.blank? %>` not valid syntax?

I'm having trouble getting erblint to recognize a rubocop config, and I'm wondering if it's related to this

**Comment by RST-J** [comment]
Because the `end` is missing for the `unless` statement.
`ruby -e 'unless 1.nil?'` yields
```
-e:1: syntax error, unexpected end-of-input
unless 1.nil?
             ^
```

**Comment by oliverbarnes** [comment]
ah, I see - it doesn't recognise the following `end`. I understand now the point about each erb tag parsed in isolation. thanks @RST-J

**Comment by tleish** [comment]
Is there a reason erb lint could not re-create the erb with just the code nodes so that rubocop could analyze ruby with multiple erb tags?

**Comment by RST-J** [comment]
Technically this can be done. I did that while experimenting with erb-lints RuboCop-Linter, I had the same thought. But that is not the real problem behind the idea.

If you run Rubocop without rearranging the code, then this will lead to false positives like wrong indentation, and empty lines.

To fix that, we could rearrange the code and keep track of the transformations. The RuboCop-Linter already has such a mapping to apply auto correction at the right place the actual erb source code.
But doing this for the whole ruby in an erb file brings up problems that do not exist for a single tag.
How to handle multiple tags on the same line? Probably add a new line for each tag after the first, but is that always right? What are the rules to consistently transform indentation. How to translate back auto corrections for multi-line tags?

In both cases there are issues with certain cops. E.g. `Style/EmptyElse` which would simply remove the `else` from the following code:
```erb
<% if foo %>
  <p>bar</p>
<% else %>
  <p>baz</p>
<% end %>
```
A similar problem with auto corrections of [Style/IfUnlessModifier](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/IfUnlessModifier).

And this is just what popped up while playing around with toy examples. It would be necessary to examine all cops for such problems and filter out those producing false positives and unsafe corrections in this setting. And are there cops which only produce false positives under certain circumstances (wrong indentation within a multi-line tag is not a false positive)?
It is rather a question of complexity/effort than of possibility, I guess.

**Comment by tleish** [comment]
Makes sense.

For us, we don't use RuboCop on erb files for indentation or blank lines, but rather for code structure.  This is more important for us.  We disable the rubocop blank lines and indentations.

We assumed that this was handling all ERB tabs, not just ERB with complete Ruby.  It wasn't until after having this in place for 6 months that we discovered one day some code that we felt should not have gotten past our CI pipeline.  After investigation and stepping through this code, we discovered the issue which took us to this thread.  

Would you be willing to consider a config flag to keep the current way by default but allow enabling combining all ruby?  I would think the right place for this would be in the .erb-lint.yml file.  Initial thought on this might be to add an option like `analyze_all_ruby`:

However, then you'll get other people complaining "why wouldn't you analyze all ruby" or "this options creates false positives for indentation",

Instead, I would call the option something like `dangerously_analyze_all_ruby` (similar to React: [dangerouslysetinnerhtml](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml)).  Then, if people see this setting they will think things like "why wouldn't you analyze all ruby AND why is this dangerous" which would lead them to documentation that explains the limitations of the ERB Lint with RuboCop and what problems they could encounter when using it.

```yaml
---
linters:
  Rubocop:
    enabled: true
    dangerously_analyze_all_ruby: true
    rubocop_config:
      inherit_from: .rubocop.yml
```

**Comment by tleish** [comment]
Any chance we could consider this as a configuration option?

**Comment by EiNSTeiN-** [comment]
My thinking around this is combining all ruby together would result in false positives at best, or wrong results at worse, plus the fact that it wouldn't be auto-correctible. We'd need to disable tons of cops making it not useful in most cases.

**Comment by tleish** [comment]
The way we (and others) use erb_lint with rubocop, we would not get false positives.  If someone did, using my suggestion they would have to set the configuration option titled `dangerously_analyze_all_ruby` (see example above), which names communicates that this could cause issues.
