### ISSUE TITLE
Update gemspec homepage to help us find the current repo

### ISSUE THREAD

**Issue by jlw** [Shopify/erb-lint#108]
When I search for this gem on rubygems.org, the only link there takes me to the original repo that hasn't been updated in a couple years - if I hadn't been paying attention to the version history, I would assume that the gem was abandoned and not even try to install it.

Some people may not think to look under that repo's forks to discover that this is the current repo for the gem's development.

**Comment by EiNSTeiN-** [comment]
Closed by #109
