### ISSUE TITLE
Gemspec and rubocop.yml still reference ruby 2.3

### ISSUE THREAD

**Issue by EiNSTeiN-** [Shopify/erb-lint#133]
> that is not supported in ruby 2.3

I see. The reason why I'm asking is because the `.gemspec` file still mentions 2.3, so does `.rubocop.yml` and the README.

https://github.com/Shopify/erb-lint/blob/f0d65d75d0d93e7cc1632421e55159847e0f60a3/erb_lint.gemspec#L21
https://github.com/Shopify/erb-lint/blob/f0d65d75d0d93e7cc1632421e55159847e0f60a3/.rubocop.yml#L5
https://github.com/Shopify/erb-lint/blob/f0d65d75d0d93e7cc1632421e55159847e0f60a3/README.md#requirements

> Support of Ruby 2.3 has ended

I realize that, however that sometimes doesn't directly correlate with what gems generally support, though. :)

_Originally posted by @aried3r in https://github.com/Shopify/erb-lint/pull/131#issuecomment-508506804_

**Comment by mvz** [comment]
This seems to have been fixed in #134.

**Comment by brendo** [comment]
> This seems to have been fixed in #134.

Agree, closing 👍
