### ISSUE TITLE
Support Rubocop 0.80

### ISSUE THREAD

**Issue by rhymes** [Shopify/erb-lint#156]
Rubocop 0.80 has been released with the following changelog: https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md#0800-2020-02-18

This gem though is tied to `0.79.x`:

https://github.com/Shopify/erb-lint/blob/44b4b9629872bc952f76ea9f5a99fa738d0b832c/erb_lint.gemspec#L25

**Comment by jcoyne** [comment]
I think this is fixed in #161

**Comment by rhymes** [comment]
Looks like it! Hopefull it'll be released soon :) Thanks for pointing that out @jcoyne!

**Comment by jcoyne** [comment]
@rhymes it was in the latest release.

**Comment by rhymes** [comment]
Mmm I don't think so, the latest [erb_lint on rubygems](https://rubygems.org/gems/erb_lint/versions/0.0.32) still points to `~> 0.79`. Same in our `Gemfile.lock`:

```yaml
    erb_lint (0.0.32)
      activesupport
      better_html (~> 1.0.7)
      html_tokenizer
      rainbow
      rubocop (~> 0.79)
      smart_properties
```

maybe it wasn't published to Rubygems?

**Comment by jcoyne** [comment]
`~> 0.79` matches with `0.80.0`

**Comment by rhymes** [comment]
OMG you're right, sorry @jcoyne :-( I didn't check which version of Rubocop we were running.

Closing this!
