### ISSUE TITLE
Gemfile.lock should not be under source control

### ISSUE THREAD

**Issue by marcandre** [Shopify/erb-lint#175]
It is the CI's job to insure that difference version of the dependencies are ok.

This does *not* imply the `Gemfile.lock` should be under source control.

The reasons why it should not be committed for gems still stand. Please follow established community guidelines.

From #41
> "That approach is actually not ideal since any developers should have all tests passed as soon as they clone the repo. This might not be the case because all developers could have multiple different dependencies version"

If tests are not passing for a developer because he happens to have a combination of dependencies that don't work, then this is an issue that needs to be fixed (by either having the right specifications in the `gemspec` or by fixing the gem)! Moreover it may be an indication that the CI is not testing enough different combinations of the dependencies. Committing the `Gemfile.lock` to avoid a bad gemspec specification is the wrong approach to fix this problem.

FWIW, I just cloned this repo and I get:

```
$ bundle --version
Traceback (most recent call last):
	4: from /Users/work/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:24:in `<main>'
	3: from /Users/work/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:24:in `eval'
	2: from /Users/work/.rvm/rubies/ruby-2.7.1/bin/bundle:23:in `<main>'
	1: from /Users/work/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/rubygems.rb:294:in `activate_bin_path'
/Users/work/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (1.17.3) required by your /Users/work/erb-lint/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.17.3`
```

Annoying I'd have to install a particularly old version of bundler to install run the specs.

Trying out any updated version of a dependency (even a dev one) will make my repo dirty.

I recommend going the other direction, i.e. git-ignoring `Gemfile.lock` and `Gemfile.local`, and that `Gemfile` loads `Gemfile.local` if present. This enables developers to test with any dependency versions they want to locally (including local repos) without having to make their repo dirty. Features/Bugs that happen to depend on a particular dependency version will be caught by the CI, as they should.

**Comment by rafaelfranca** [comment]
> The reasons why it should not be committed for gems still stand. Please follow established community guidelines.

I think we are following the guidelines. https://bundler.io/blog/2018/01/17/making-gem-development-a-little-better.html

Thank you for the pull request.

**Comment by marcandre** [comment]
Yes, indeed, I should have closed this request.

I disagree with the changed guidelines, but that's a meta-fight I'm not willing to tackle.
