### ISSUE TITLE
Issues with ERB + AlpineJS

### ISSUE THREAD

**Issue by coderberry** [Shopify/erb-lint#177]
I have an erb file that is failing the lint verification. Here's the snippet:

```html
<button @click="open = true"
  data-action="click->modal#open"
  class="text-white bg-indigo-500 hover:bg-indigo-700 inline-flex py-3 px-5 rounded-lg items-center focus:shadow-outline shadow">
  <span class="flex items-start flex-col leading-none">
    <span class="text-sm mb-1">Are you a marketer?</span>
    <span class="title-font font-medium">Start an ethical ad campaign</span>
  </span>
</button>
```

The lint fails with the `@click` attribute. Is there a way to ensure these are not causing the lint failure?

**Comment by coderberry** [comment]
This is a non-issue. It's related to the[ better-html](https://github.com/Shopify/better-html) gem.

I had to add the following initializer in my Rails app to make this work:

```ruby better_html.rb
BetterHtml.configure do |config|
  config.partial_attribute_name_pattern = /\A[a-zA-Z0-9\-\:\@\.]+\z/
end
```

**Comment by clinejj** [comment]
I'm still experiencing this issue, with a snippet like this:

```html
<nav x-data="{ open: false }" @keydown.window.escape="open = false" class="bg-white border-b"></nav>
```

gives the error:

```
1:30: expected whitespace, '>', attribute name or value (at @)
```

I updated my `.better-html.yml` that is used for the ErbSafety config to be:
```yml
partial_attribute_name_pattern: !ruby/regexp /\A[a-zA-Z0-9\-\:\@\.]+\z/
```

I opened the erb_lint gem and that configuration is getting read properly, but where the lint error is being generated from isn't using this configuration.

**Comment by 5mutawa** [comment]
The simplest solution is to use `x-on:` instead of the shortcut `@`
For example instead of:
```html
<button @click="alert('Hello World!')">Say Hi</button>
```
Use:
```html
<button x-on:click="alert('Hello World!')">Say Hi</button>
```
