### ISSUE TITLE
New cop: Rendering partials without prefix

### ISSUE THREAD

**Issue by MatheusRich** [Shopify/erb-lint#206]
Rendering a partial without a prefix is slower than calling it with a prefix.

So, calling

```ruby
<%= render "menu" %>
```

is slower than

```ruby
<%= render "shared/menu" %>
```

This happens because it triggers more loops inside ActionView::PathSet [_find_all method](https://github.com/rails/rails/blob/5a0fce7d4ecd152e883877bc5a6a11af54207fde/actionview/lib/action_view/path_set.rb#L72-L85)

More details can be found in [this article](https://medium.com/wantedly-engineering/a-simple-fix-to-improve-partial-rendering-speed-by-30-in-a-large-rails-application-9696a92f4ae1).

**Comment by rafaelfranca** [comment]
Thank you for the issue but we have no interest of adding new cops for performance related issue. Performance in my opinion only matters when it is measured in real case scenarios. View that are rendered once a day have no reason to change their code.
