### ISSUE TITLE
Do not fail on `info` offenses

### ISSUE THREAD

**Issue by llekn** [Shopify/erb-lint#220]
[Rubocop's default behavior is to report but not return a non-zero value on cops with severity `info`](https://docs.rubocop.org/rubocop/configuration.html#severity).

I would like to take advantage of this to progressively activate cops (first activate them with severity `info` so offenses will be reported on linters but won't cause pipeline to fail) which works as intended on rubocop but not on `erblint`.

Is there any way to make `erblint` behave exactly as `rubocop` in this case? (ie return a non-zero value only when offenses not marked as `info` fail)

**Comment by rafaelfranca** [comment]
I don't think this is implemented yet but I'd be happy to merge a PR implementing this behavior. Do you want to give it a try?

**Comment by llekn** [comment]
Hi @rafaelfranca 👋  thank you very much for the response!

I see. I will give it a shot but on the weekend as I'm a little bit short on time right now.
