### ISSUE TITLE
ParserErrors linter fails on AlpineJS attributes

### ISSUE THREAD

**Issue by clinejj** [Shopify/erb-lint#221]
Stemming somewhat from https://github.com/Shopify/erb-lint/issues/177, I have an issue with some ERB files I have that use AlpineJS directives. For example, this snippet:

```html
<nav x-data="{ open: false }" @keydown.window.escape="open = false" class="bg-white border-b"></nav>
```

gives the error:

```
1:30: expected whitespace, '>', attribute name or value (at @)
```

when running `bundle exec erblint --enable-linters parser_errors --lint-all -f compact`

It doesn't appear that the default parser doesn't accept configuration for what characters to allow for attribute names.

**Comment by rafaelfranca** [comment]
That is true. Given we are not users of AlpineJS, I'd say that if you have interest in building support, feel free to open a PR.

**Comment by clinejj** [comment]
Sure, it looks like this issue might better be filed in better-html as the parser doesn't currently accept any configuration options? While the runtime checks there do (see https://github.com/Shopify/better-html/blob/master/lib/better_html/better_erb/runtime_checks.rb), that runs on top of the parser which seems unnecessary duplicative to implement here. Thoughts on how to approach?

**Comment by rafaelfranca** [comment]
Good point. It makes sense to change better-html to be less restrictive with configuration and reuse the right version of the better-html parser here.

**Comment by clinejj** [comment]
Opened issue in `better-html` above, will close this for the time being.
