### ISSUE TITLE
`&rarr;` allowed in HardCodedString

### ISSUE THREAD

**Issue by justinko** [Shopify/erb-lint#226]
Hi, is there any particular reason why something like `&rarr;` isn't in the blacklist here: https://github.com/Shopify/erb-lint/blob/master/lib/erb_lint/linters/hard_coded_string.rb#L22

Or at least a way to add to the list?

🙏

**Comment by rafaelfranca** [comment]
No reason. To add to the list just open a PR, and if you want please add all the other entities that makes sense.
