### ISSUE TITLE
erb_lint version regresses from 0.1.3 to 0.0.4 when running command bundle update erb_lint

### ISSUE THREAD

**Issue by ccasabona** [Shopify/erb-lint#271]
When running the command:

```
bundle update erb_lint
```

erb_lint version regresses from 0.1.3 to 0.0.4.

```
Note: erb_lint version regressed from 0.1.3 to 0.0.4
Bundle updated!


```
Running the bundle outdated command shows this:

```
Gem                 Current   Latest    Requested  Groups
erb_lint            0.0.4     0.1.3     >= 0       development, test

```
Version 0.0.4 allows updating better_html to 2.0.1.  Since gem version do not usually regress, is this a concern?

**Comment by rafaelfranca** [comment]
Not a concern, and it is how bundler works. To fix this you need to specify what is the minimum version of erb_lint your application wants to use in the Gemfile. Regardless I released a 0.2.0 version that should also works with better_html 2.0 and that should make sure it doesn't regress anymore.
