### ISSUE TITLE
Request for opinions about RuboCop's template support API

### ISSUE THREAD

**Issue by r7kamura** [Shopify/erb-lint#274]
## About

We are now working on adding an API to RuboCop to support templates like ERB, Haml and Slim.

- https://github.com/rubocop/rubocop/pull/10839

I believe erb_lint is also working on the same goal for eRuby templates in its Rubocop Linter feature. If you don't mind, would you care to share some thoughts on the API we are trying to add?

## Schedule

I hope to finish collecting feedback by **November 30, 2022**, and then release the API (maybe in January 2023 or so).

## Related Issues

- https://github.com/sds/haml-lint/issues/379
- https://github.com/sds/slim-lint/issues/142

**Comment by zachfeldman** [comment]
This seems awesome! I only recently started trying to contribute to `erb-lint` with https://github.com/Shopify/erb-lint/pull/268, but I was wondering the whole time why `erb-lint` isn't just a part of `rubocop`. Then it could maybe leverage `rubocop`s existing parallelization. Does your solution allow that?

**Comment by r7kamura** [comment]
Yes, I think RuboCop's file cache will work well for ERB templates once this template support feature is merged.

However, just to be clear, it does not replace all the features of erb-lint, but only those about RuboCop. So, if we want to lint the syntactic part of ERB (e.g. if there is a newline at the end of the ERB file), we will still use erb-lint, and it would be better to have file cache feature at https://github.com/Shopify/erb-lint/pull/268 to improve speed there.

**Comment by r7kamura** [comment]
I'm going to close this issue as it has done its purpose. Thank you for feedback 👍
