### ISSUE TITLE
Cache not working on 0.4.0?

### ISSUE THREAD

**Issue by joshuapinter** [Shopify/erb-lint#318]
Hmmm, just upgraded from 0.3.1 to 0.4.0 and the caching doesn't seem to be working. Every time I run `erblint` it says: 

```
Cache being created for the first time, skipping prune
```

I looked through the code changes since 0.3.1 and I can't see anything obvious that would break the caching functionality but maybe somebody more familiar to take a look.

Anybody else seeing this?

**Comment by franklinhu** [comment]
I'm also seeing this behavior in 0.4.0

**Comment by joshuapinter** [comment]
Glad I'm not the only one! 

Looks like @ianfleeton found a solution and issued a PR. Just not merged yet.

**Comment by joshuapinter** [comment]
Just want to add, #325 by @ianfleeton fixes my issue. Let's get that merged in please.

**Comment by joshuapinter** [comment]
Fixed in #325.

**Comment by joshuapinter** [comment]
🙏  @ianfleeton
