### ISSUE TITLE
'exclude' option not working?

### ISSUE THREAD

**Issue by aried3r** [Shopify/erb-lint#87]
Hey!

I just found this project thanks to an [issue in rubocop](https://github.com/rubocop-hq/rubocop/issues/6141#issuecomment-409327499). Thanks, it looks awesome and I already found some layout issues thanks to it! :)

I was playing around when I found that using the CLI does not respect the `exclude` options of linters. I didn't find anything in the code that would suggest that this option would override the local linter config.

```
$ erblint --lint-all
Linting 2 files with 13 linters...

String not translated: ErbLintExclude
In file: app/views/layouts/application.html.erb:4

String not translated: /* Email styles need to be inline */
In file: app/views/layouts/mailer.html.erb:6

2 error(s) were found in ERB files
```

```YAML
# .erb-lint.yml

---
linters:
  HardCodedString:
    enabled: true
    exclude:
      - 'app/views/**/*'

```

I also tried `'app/views/**'` which I think is the wrong globbing syntax anyway.

Reproduction in this repo: https://github.com/aried3r/erb-lint-exclude

**Comment by EiNSTeiN-** [comment]
I think the exclude path is compared to the full path of the ProcessedSource object (https://github.com/Shopify/erb-lint/blob/c7392218e7443724dfa8b907e0d687a429918161/lib/erb_lint/runner.rb#L22-L23) not the relative path. This is probably wrong but in the meantime you can try `**/` at the beginning of your glob.

**Comment by aried3r** [comment]
Ah, good point, that worked, thanks! I checked the occurrences of `exclude` and only found one example, I didn't think much of it. Here's what I found, in case you wanna know :)

https://github.com/Shopify/erb-lint/blob/b131ef57a7ed23f15e89e3bf8d99325c993c75fd/spec/erb_lint/runner_spec.rb#L89-L90
https://github.com/Shopify/erb-lint/blob/ee193640de1dea2922e800d987f08f423e20bc7e/spec/erb_lint/linter_config_spec.rb#L101
https://github.com/Shopify/erb-lint/blob/b131ef57a7ed23f15e89e3bf8d99325c993c75fd/spec/erb_lint/runner_config_spec.rb#L92-L95
https://github.com/Shopify/erb-lint/blob/0c5eb9a2e6a0c3e38579cebf586c49f3941c8856/README.md#L73-L74

> This is probably wrong

Well, depends, if the documentation is alright it's ok. But having it work like RuboCop would be a plus, yes.

Btw, a more general question, is it ok to report issues or is this repo still in the 'exploring' phase @Shopify?

**Comment by EiNSTeiN-** [comment]
Yes it's OK to report issues, I may not be quick to fix them though :(

**Comment by alflanagan** [comment]
The correct syntax for excludes should definitely be in the README. I was about to uninstall until I found this (in my case, it was the "vendor" directory).

**Comment by rafaelfranca** [comment]
It should be working now. Thank you for the issue.

**Comment by boardfish** [comment]
This issue is occurring for me. I have the following config:

```yml
---
EnableDefaultLinters: true
glob: "**/*.{html,text,js}{+*,}.erb"
exclude:
  - 'vendor/**/*'
  - 'node_modules/**/*'
```

I've also tried with `**/` preceding the paths. `vendor` is still targeted. I'm calling it as follows:

`bundle exec erblint --config .erb-lint.yml --lint-all`

Manually specifying the config shouldn't really be necessary, but I'm doing that as a sanity check. Also, I wonder if `--lint-all` should be the default behavior (similar to `rubocop`).
