### ISSUE TITLE
Stop using Colorize gem

### ISSUE THREAD

**Issue by bquorning** [Shopify/erb-lint#93]
I am not a fan of the dependency on the `Colorize` gem, since it monkey-patches `String`:
```
» ruby -e 'puts String.colors'
-e:1:in `<main>': undefined method `colors' for String:Class (NoMethodError)
» ruby -r colorize -e 'puts String.colors'
black
light_black
red
[…]
```

Would you be open to a pull request switching to use e.g. [Rainbow](https://rubygems.org/gems/rainbow) instead?

**Comment by EiNSTeiN-** [comment]
yes, I'm open to that

**Comment by md5** [comment]
The `colorize` gem also uses GPL as opposed to MIT, which could cause some organizations pause. Looks like `rainbow` uses MIT.
